### PR TITLE
add Conv singlestage

### PR DESCRIPTION
**Pull request by leiwen83**
This commit set add singlestage conv for cutlass

### CODE REVIEW

**Comment by hwu36** [comment]
Thanks, I will take a look and run the tests.  If any change is needed, I will do it myself and push to your branch.

**Comment by mnicely** [comment]
@leiwen83 can you provide performance results to justify this PR?

**Comment by leiwen83** [comment]
> @leiwen83 can you provide performance results to justify this PR?

Seem to me there is no performance gain for this single stage conv being added. So maybe we could close this PR for now.

**Comment by hwu36** [comment]
This is a useful feature for T4 or maybe small ampere cards.  I will work on it hopefully this month.

**Comment by manishucsd** [comment]
We do have [singlestage mma](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/mma_singlestage.h) pipeline for GEMMs. Do we have some use cases for T4 where single stage wins over 2-staged pipeline?

**Comment by hwu36** [comment]
> We do have [singlestage mma](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/mma_singlestage.h) pipeline for GEMMs. Do we have some use cases for T4 where single stage wins over 2-staged pipeline?

Yes, most kernels picked by cublas on t4 are single stage ones.

**Comment by hwu36** [comment]
Hi @leiwen83 ,

Sorry for the delay.  I am working on this one now.  Have you tested your code in any way?

**Pull request closed without merging**
