### PR TITLE
Add support for sparse GEMM with visitor epilogue

### PR DESCRIPTION
**Pull request by alexsamardzic**
@apuaaChen

### CODE REVIEW

**Comment by alexsamardzic** [comment]
This PR makes it possible to combine sparse GEMM with EVT epilogues.  Besides adding `SparseGemmWithVisitor` and `DefaultSparseGemmWithVisitor` classes to `cutlass::gemm::kernel` namespace, as well as `SparseGemmWithVisitor` class to `cutlass::gemm::device` namespace, it also includes an example of use, modeled after existing `15_ampere_sparse_tensorop_gemm`, but with bias addition implemented as an EVT epilogue.

Some items to discuss about PR:

1. I'm not sure that I understand properly the purpose of the first argument of `cutlass::epilogue::threadblock::EpilogueWithVisitorCallbacks` template, so instantiation of this template in `include/cutlass/gemm/kernel/default_gemm_sparse_with_visitor.h` may need an adjustment.  In particular, I find it confusing that `ElementC`, `LayoutC` and `ElementEpilogue` are to be specified here, when these have no clear meaning for the EVT epilogue.
2. Tried first to go without `cutlass::gemm::device::SparseGemmWithVisitor` class, and to utilize `SparseGemmWithVisitor` kernel from `GemmUniversal` device class instead, but to no avail; would appreciate comments on is it possible and how actually to use `SparseGemm`/`SparseGemmWithVisitor` kernels this way.
3. For intended use of `SparseGemmWithVisitor` in my case, and that is about supporting sparse GEMM on tensor cores in PyTorch project, it is imprortant too to have it exposed through `cutlass_library`, so I would also appreciate any suggestions on how to do it.  In particular, `cutlass::gemm::device::SparseGemmWithVisitor` template arguments differ from corresponding `cutlass::gemm::device::SparseGemm` class (for example, `ElementC`/`LayoutC` arguments are missing in my implementation of `SparseGemmWithVisitor` counterpart, and I'm not sure is that going to be a problem).

**Comment by hwu36** [comment]
@apuaaChen @jackkosaian @richardmcai , could you please review it first?  we can include it in 3.4

**Comment by apuaaChen** [comment]
Hi @alexsamardzic Thank you for your effort! This MR looks good to me. My small suggestions are listed above, the basic idea is to use the original non-visitor implementation from CUTLASS as the base class and derive anything unrelated to epilogue from them. This could avoid some duplications.

**Comment by alexsamardzic** [comment]
Hi @apuaaChen, thanks for your comments.  Just to make it clear, when you mention derivation in your first comment, do you have `cutlass::gemm::kernel` or `cutlass::gemm::device` classes on your mind (or both)?

**Comment by apuaaChen** [comment]
> Hi @apuaaChen, thanks for your comments. Just to make it clear, when you mention derivation in your first comment, do you have `cutlass::gemm::kernel` or `cutlass::gemm::device` classes on your mind (or both)?

Hi @alexsamardzic, I think both `kernel` and `device` should be benefited from derivation.

**Comment by alexsamardzic** [comment]
Sorry for the delay, I just pushed a commit that added `ElementC`/`LayoutC` into visitor version of sparse GEMM, and also refactored classes within `cutlass/gemm/kernel` so that the relation between non-visitor and visitor version is alike to relation between corresponding non-visitor and visitor universal GEMM classes (which means: visitor version inherits non-visitor version, base `Params` class is extracted into separate file etc.).  So - it would be great if you could check it now (please look [here](https://github.com/NVIDIA/cutlass/pull/1189/files), i.e. look at these two commits as whole, as I'm going to squash them if this looks OK), and let me know your comments.

**Comment by apuaaChen** [comment]
> Sorry for the delay, I just pushed a commit that added `ElementC`/`LayoutC` into visitor version of sparse GEMM, and also refactored classes within `cutlass/gemm/kernel` so that the relation between non-visitor and visitor version is alike to relation between corresponding non-visitor and visitor universal GEMM classes (which means: visitor version inherits non-visitor version, base `Params` class is extracted into separate file etc.). So - it would be great if you could check it now (please look [here](https://github.com/NVIDIA/cutlass/pull/1189/files), i.e. look at these two commits as whole, as I'm going to squash them if this looks OK), and let me know your comments.

Hi @alexsamardzic. I went through the updated code, it looks much better now. Two minor comments:

- For the kernel-level template, you can take a look at https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/kernel/default_gemm_universal_with_visitor.h, which can further simplify your code
- I like the `params_sparse_base.h`, which helps avoid code duplication. But I'm not sure if it is ok to change the `params` struct of `sparse_gemm.h`, maybe @hwu36 can give more comments here

**Comment by alexsamardzic** [comment]
Thanks for checking latest changes.

>     * For the kernel-level template, you can take a look at https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/kernel/default_gemm_universal_with_visitor.h, which can further simplify your code

I've added `cutlass/gemm/kernel/default_gemm_sparse_with_visitor.h`, I think it's even simpler than corresponding `default_gemm_universal_with_visitor.h` - namely, I'm skipping `using GemmBase = ...` and am building my `BaseEpilogue` directly.  Do you have anything specific that you want changed here?

>     * I like the `params_sparse_base.h`, which helps avoid code duplication. But I'm not sure if it is ok to change the `params` struct of `sparse_gemm.h`, maybe @hwu36 can give more comments here

Ok.  Just a comment here:  The `SparseGemm::Params` is exactly the same as before, it's just that what it shares with `SparseGemmWithEpilogueVisitor::Params` is now extracted into common base class.  This is, again, exactly how `GemmUniversal::Params`/`GemmWithEpilogueVisitor::Params` work (in their case, there is even some duplication actually).

**Comment by alexsamardzic** [comment]
FWIW, [here](https://github.com/NVIDIA/cutlass/files/13601599/sparse-patch.txt) is a patch to be applied on top of f87bf8ae0a0b56a8a033335bc45c2f24053a640f, that makes both `cutlass::gemm::kernel::SparseGemm` and `cutlass::gemm::kernel::SparseGemmWithVisitor` inheriting from common base class (instead of later inheriting from former, that I posted previously).  This may be also an approach to consider.

**Comment by hwu36** [comment]
fyi,  i am working on this one now.

**Comment by alexsamardzic** [comment]
> fyi, i am working on this one now.

Thanks.  Just to clarify - by "working on this", do you mean reviewing my PR or working on this feature independently?

**Comment by hwu36** [comment]
i mean working on merging your MR.  you know there is a process that i have to go through.  if i need to change your code, i can do it directly in this pr.

**Comment by alexsamardzic** [comment]
Of course, thanks!   Please let me know if further changes are needed from my side, in particular w.r.t. @apuaaChen request to refactor the code so that duplication between existing sparse GEMM and newly added sparse GEMM with visitor epilogue.

Also, it was my intention to check is there anything needed to add support for sparse GEMM with visitor epilogue into `cutlass_library` - this is something that I also need for my PyTorch work.  But I can do that through a new PR after this one merged.

**Review by hwu36 — APPROVED** [review]

**Pull request merged**
