### PR TITLE
Typo Fixes

### PR DESCRIPTION
**Pull request by tjingrant**
Was reading into the codebase and found some typos. 

Please let me know if there're beginner-friendly tasks I can help with.

### CODE REVIEW

**Review by hwu36 — APPROVED** [review]

**Comment by hwu36** [comment]
There are many things can be done in cutlass, but I'd like to know your interests and bandwidth first.

**Comment by tjingrant** [comment]
My goal is to to use cutlass in my upcoming research projects. I'm generally interested in working on sparsity related features in the context of ML/DL workload, though I don't have any Turing/Ampere GPUs at hand yet, so I'm mostly playing around with software-level sparsity as of now on V100. (On a related note, is there any plan to upstream this related line of [work](https://github.com/YulhwaKim/cutlass_tilesparse) done by nvidia to cutlass?) 

I'm also open to take on generic tasks as warm-up and understand the codebase. My bandwidth will vary, but assuming that it aligns well with my research objective, I'd say 3-4 full days every 2 weeks over the summer.

**Comment by hwu36** [comment]
Great.

When you get an ampere card, we could use your help on cleaning sparse gemm code and then adding sparse conv. 

Before you get an ampere card, do you have interest in fixing random bugs like gemv, wmma in profiler, etc.?  These were working before, but not actively maintained anymore.

**Comment by tjingrant** [comment]
Yes, I can take a crack at fixing wmma in profiler as mentioned [here](https://github.com/NVIDIA/cutlass/discussions/288)!

**Comment by hwu36** [comment]
Thank you.  The disabled gemv tests are in https://github.com/NVIDIA/cutlass/tree/master/test/unit/gemm/kernel

**Pull request merged**
